### ISSUE TITLE
언어 설정 적용하기

### ISSUE THREAD

**Issue by narahub123** [narahub123/playground-fe#8]
## ✔️ Issue
- 언어 설정 적용하기

## 📝 To-do
- [x] 접속한 언어 혹은 국가 알아내기
- [x] 언어 설정 생성하기 
- [x] 언어 변경 버튼 생성하기 
- [x] settings에 언어 설정 저장하기

## 결과
![508](https://github.com/user-attachments/assets/cebdb40c-59e8-4766-ab02-517574cb1f98)

## 🛠 Working time
- **기간**: 3시간
- **시작일**: 2024.09.24
- **종료일**: 2024.09.24

**Comment by narahub123** [comment]
완료
